#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
# xrdb ~/.Xresources-nord &	# Uncomment to use Xresources colors/settings on startup
xrdb ~/.config/x11/xresources-nord &	# Uncomment to use Xresources colors/settings on startup
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xcompmgr &
chadbar &
# picom &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xrandr --output eDP1 --brightness 1.0
clipmenud&
redshift -l 47.2744317:-1.6893901&
